version: '3.8'

volumes:
  mariadb_vol:
  mongo_vol:
  postegresql_vol:
  redis_vol:

networks:
   my-netservivces:
      driver: bridge

services:
  mariadb:
    image: mariadb:10.7.1
    ports:
    - 3306:3306
    networks:
    - my-netservivces 
    volumes:
    - mariadb_vol:/data/db
    restart: always
    environment:
      MARIADB_USER: mariadbuser 
      MARIADB_PASSWORD: mariadbpwd
      MARIADB_ROOT_PASSWORD: xpto123

  phpmyadmin_mariadb:
    image: phpmyadmin:latest
    ports:
    - 8083:80
    networks:
    - my-netservivces
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xpto123
      MYSQL_USER: mariadbuser
      MYSQL_PASSWORD: mariadbpwd
      PMA_HOST: mariadb

   mongodb:
    image: mongo:5.0.6
    ports: 
    - 27017:27017
    networks:
    - my-netservivces
    volumes:
    - mongo_vol:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  mongo-express:
    image: mongo-express:0.54
    ports:
    - 8084:8081
    networks:
    - my-netservivces
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: default
      ME_CONFIG_BASICAUTH_USERNAME: mongouser
      ME_CONFIG_BASICAUTH_PASSWORD: mongopwd
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: db

  postgresql:
    image: postgres:9.6.24
    ports:
    - 5432:5432
    networks:
    - my-netservivces 
    volumes:
    - postegresql_vol:/data/db
    restart: always
    environment:
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: xpto123

  pgadmin:
    image: dpage/pgadmin4:6.5
    ports:
    - 8081:8081
    networks:
    - my-netservivces
    environment:
      PGADMIN_DEFAULT_EMAIL: "priscilaalv@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: xpto123
      PGADMIN_LISTEN_PORT: 8081

  redis:
    image: redis:7.0-rc1
    ports:
    - 6379:6379
    networks:
    - my-netservivces 
    volumes:
    - redis_vol:/data/db
    restart: always
    
  rediscommander:
    image: rediscommander/redis-commander:latest
    ports:
    - 8082:8081
    networks:
    - my-netservivces
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis