version: '3.8'

volumes:
  mongo_vol:

networks:
   my-netservivces:
      driver: bridge

services:
  mongo:
    image: mongo:5.0.6
    ports: 
    - 27017:27017
    networks:
    - my-netservivces
    volumes:
    - mongo_vol:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example